# Generated by Django 5.2.3 on 2025-08-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('rollno', models.IntegerField(default='',max_length=100)),
                ('name', models.CharField(default='', max_length=50)),
                ('hindi', models.IntegerField(default='', max_length=3)),
                ('gujarati', models.IntegerField(default='', max_length=3)),
                ('ss', models.IntegerField(default='', max_length=3)),
                ('total', models.IntegerField(default='', max_length=3)),
                ('min_marks', models.IntegerField(default='', max_length=3)),
                ('max_marks', models.IntegerField(default='', max_length=3)),
                ('percentage', models.FloatField(default='', max_length=5)),
                ('grade', models.CharField(default='', max_length=2)),
            ],
        ),
    ]
